--- #YAML FILE START
app.app_diag: "CRITICAL" #app/app_MODULE/app_EXAMPLE.py

__main__: "DEBUG"

##### app #####
app.app_SALG: "INFO"
app.app_DIAG: "WARN"
app.app_STRG: "WARN"

##### mid #####
mid.mid_pwr: "WARN"
mid.mid_dabs: "WARN"
mid.mid_str: "WARN"
mid.mid_meas: "WARN"

##### drv ######
drv.drv_can: "DEBUG"
drv.drv_scp: "CRITICAL"

drv.drv_uepc: "INFO"
drv.drv_db: "ERROR"


drv.drv_pwr: "WARN"
drv.drv_ea: "CRITICAL"
drv.drv_rs: "CRITICAL"


##### sys #####
sys_abs.sys_shd: "CRITICAL"
sys_abs.sys_conf: "CRITICAL"
sys_abs.sys_log: "CRITICAL"


file_handlers: {
  # "log_can" : [ drv.drv_can, drv.drv_epc ],
}